### ISSUE TITLE
Secret Key in test.yml

### ISSUE THREAD

**Issue by Ichi1234** [Pawat-Sarnchawanakit/ku-polls#20]
tests.yml in GitHub should not contain a secret key. Instead, use a repository secret in the repository settings. Don't forget to generate a new key! You can follow these instructions to generate a new key.  (https://www.makeuseof.com/django-secret-key-generate-new/)

**Comment by Pawat-Sarnchawanakit** [comment]
It's just a random key I generated especially for the purpose of testing. Not really a secret.
It won't be used in production.
