### ISSUE TITLE
Another User can't vote already vote user-created polls.

### ISSUE THREAD

**Issue by Ichi1234** [Pawat-Sarnchawanakit/ku-polls#22]
In user-created polls, each user can only vote once. When another user logs in, a notification informs them that the poll has already been voted on. (This might relate to issue #21 )

**Comment by Pawat-Sarnchawanakit** [comment]
This seems to be related to the CLIENT allow option as it is the default option for user-created poll whereas the polls created in the database has allow set to AUTH.
CLIENT option allows polls to be answered without having to be logged in but will only allow anonymous users to answer only once and they can't change their answers. However, it seems that this restriction seems to be applied to authenticated users as well.
