### ISSUE TITLE
Change README.md section alignment.

### ISSUE THREAD

**Issue by Ichi1234** [Pawat-Sarnchawanakit/ku-polls#24]
I suggest that GitHub README.md after the "Installation" topic. Should the "Running the Application" section contain the installation info again? (Maybe you should replace "Running the Application" with the "Starting the Development Server" section from the installation guide to README.md and remove exist.)

**Comment by Pawat-Sarnchawanakit** [comment]
Running the Application doesn't contain the installation info again. It just shows how to reactivate the virtual environment and do any config changes or loading the database and how to run the development server which you might want to do again after installation.
