### ISSUE TITLE
"Create a Poll" page in non-user-friendly.

### ISSUE THREAD

**Issue by Ichi1234** [Pawat-Sarnchawanakit/ku-polls#25]
I think your "Create a Poll" page is so cool. However, it might not be user-friendly. People who aren't programmers might find it hard to understand.

I think you should make some documents to guide the project's customer. (Maybe a new button that links to the guide page or creates a guide file in the directory?)

**Comment by Pawat-Sarnchawanakit** [comment]
I will write comments in the default template to explain how to create a poll.

**Comment by Ichi1234** [comment]
Can "end:" be uncommented and set to None? It blends in too much with other comments, and users might mistake it for just a comment rather than an attribute.
