### ISSUE TITLE
Application does not conform to requirements

### ISSUE THREAD

**Issue by jbrucker** [Pawat-Sarnchawanakit/ku-polls#6]
Your KU Polls code is impressive, but it does not conform to the
requirements for Iteration 1.

That is probably why the TAs didn't grade it.

In Iteration 1 and 2:

- no users and no login
- no dependency on Node.js, Vue.js, or Javascript packages.(1)
  If you want to use Javascipt, either get the packages from a CDN server
  or include them as static content. Don't ask the TAs to install them.
- no separate "front end" and "back end". Just a single, simple Django app.
- Django config directory should be "mysite" or "config", not `ku_polls`

Sorry if this assignment is too simple for you.

You can show your skill on the team project -- where's your project proposal?

Note

1. You do *not* need Node.js to run a Javascript front-end if Django provides the backend. You can serve the front-end as static content. You can serve an entire Vue app this way.

**Comment by Pawat-Sarnchawanakit** [comment]
I've made some commits to address this issue:
1. I've renamed ku_polls folder to config.
2. I've removed the login requirements from the fixtures.
3. Vue.js is already included as static content as of iteration 2 making the requirements of Node JS unnecessary.
    I've gone and commit the prebuilt files in iteration 1 as well.
4. I've removed the Node JS requirements in README.md


`You do not need Node.js to run a Javascript front-end if Django provides the backend. You can serve the front-end as static content. You can serve an entire Vue app this way.` 

Yes you do not need Node.js to run a Javascript front-end, node was just required for packing the easily readable javascript files from the repo to minified javascript files which will be served using Django.

I'm sorry but I'm not trying to be a show off, it's just when I saw the assignment, the Django tutorial says "to insert" so I just thought I can choose any tutorial and followed it and I did just that. Afterwards when the tutorial url was placed, I had gone too far so I just keep going with what I already have.

Can you please tell the TA to grade it again?

**Comment by Pawat-Sarnchawanakit** [comment]
Fixed in c0c213c
